### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jansivans** [ivisnauskis/jr-js-task#1]
Hi! 
Thanks for your solution.
Everything is working well and looks good for me.
The only thing I have noticed you used immediately-invoked function `(async () => {})();` in excel controller.
You don't need to do this - all you need to do is simply add `async` in endpoint declaration:
```js
excelRouter.post("/", upload.single("data"), async (req, res) => {
```

**Comment by ivisnauskis** [comment]
Hi. Thanks for the feedback!
